# Generated by Django 4.1.5 on 2023-06-08 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_bg', models.ImageField(upload_to='media/')),
                ('image_little', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='QrCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='media/')),
                ('user', models.ForeignKey(default=0, on_delete=models.deletion.CASCADE, to='userpages.usermod')),
                ('user_img', models.ForeignKey(on_delete=models.deletion.CASCADE, to='editor.example')),
            ],
        ),
    ]
