# Generated by Django 4.1.5 on 2023-06-07 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QrCode',
        ),
    ]
