# Generated by Django 4.1.5 on 2023-06-08 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_hol'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hol',
        ),
    ]
