# Generated by Django 4.1.5 on 2023-06-08 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0003_delete_hol'),
    ]

    operations = [
        migrations.CreateModel(
            name='LittleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_little', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_bg', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.RemoveField(
            model_name='qrcode',
            name='user_img',
        ),
        migrations.DeleteModel(
            name='Example',
        ),
    ]
