# Generated by Django 4.1.5 on 2023-06-12 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0005_qrcode_little_user_img_qrcode_user_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='littleimage',
            name='image_little',
        ),
        migrations.RemoveField(
            model_name='userimage',
            name='image_bg',
        ),
    ]
