# Generated by Django 4.1.5 on 2023-06-12 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0007_littleimage_image_little_userimage_image_bg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='littleimage',
            name='image_little',
        ),
        migrations.RemoveField(
            model_name='userimage',
            name='image_bg',
        ),
    ]
