# Generated by Django 4.1.5 on 2023-06-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpages', '0002_remove_usermod_qr_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.FloatField(),
        ),
    ]
