# Generated by Django 4.1.5 on 2023-06-08 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpages', '0003_alter_plan_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermod',
            name='last_payment',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
