# Generated by Django 4.1.5 on 2023-06-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpages', '0004_usermod_last_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermod',
            name='qr_amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
