# Generated by Django 4.1.5 on 2023-06-13 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpages', '0005_usermod_qr_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermod',
            name='qr_scans',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
