# Generated by Django 4.1.5 on 2023-06-15 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpages', '0006_usermod_qr_scans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='scans',
        ),
    ]
