# Generated by Django 4.1.5 on 2023-06-20 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpages', '0008_usermod_is_auth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermod',
            name='is_auth',
        ),
    ]
